import { useEffect, useMemo, useState } from 'react'
import { addLocalFocusSession, finishLocalFocusSession, getLocalFocusSessions, getLocalGoals, getLocalHabits, updateLocalFocusSession } from '../../lib/local-store'
import { getChallenges } from '../challenges/services/challenge.repository'

export function Focus() { const [sessions, setSessions] = useState(getLocalFocusSessions); const active = useMemo(() => sessions.find(item => item.status === 'active' || item.status === 'paused'), [sessions]); const [project, setProject] = useState(''); const [challengeId, setChallengeId] = useState(''); const [goalId, setGoalId] = useState(''); const [habitId, setHabitId] = useState(''); const [, tick] = useState(0); useEffect(() => { if (!active || active.status !== 'active') return; const timer = window.setInterval(() => tick(value => value + 1), 1000); return () => clearInterval(timer) }, [active]); const seconds = active ? elapsed(active) : 0
  function start() { const created = addLocalFocusSession({ started_at: new Date().toISOString(), project_name: project.trim() || null, challenge_id: challengeId || null, goal_id: goalId || null, habit_id: habitId || null }); setSessions(getLocalFocusSessions()); setProject(''); setChallengeId(created.challenge_id ?? ''); setGoalId(''); setHabitId('') }
  function pause() { if (!active) return; updateLocalFocusSession(active.id, { status: 'paused', accumulated_seconds: elapsed(active) }); setSessions(getLocalFocusSessions()) }
  function resume() { if (!active) return; updateLocalFocusSession(active.id, { status: 'active', started_at: new Date().toISOString() }); setSessions(getLocalFocusSessions()) }
  function finish() { if (!active) return; finishLocalFocusSession(active.id); setSessions(getLocalFocusSessions()) }
  function cancel() { if (!active) return; updateLocalFocusSession(active.id, { status: 'cancelled' }); setSessions(getLocalFocusSessions()) }
  const challenges = getChallenges().filter(item => item.status === 'ACTIVE'); const goals = getLocalGoals().filter(item => item.status === 'active'); const habits = getLocalHabits().filter(item => item.active); return <><header><p className="eyebrow">DEEP WORK</p><h1>Foco</h1><p>Proteja um bloco de atenção. Ao encerrar, os minutos alimentam sua Caverna automaticamente.</p></header><section className="panel focus-timer"><p className="eyebrow">{active?.status === 'active' ? 'EM FOCO' : active?.status === 'paused' ? 'PAUSADO' : 'PRONTO'}</p><strong>{formatSeconds(seconds)}</strong>{active ? <><p>{active.project_name || 'Sessão sem projeto'}</p><div className="focus-actions">{active.status === 'active' ? <button className="subtle" onClick={pause}>Pausar</button> : <button onClick={resume}>Continuar</button>}<button onClick={finish}>Encerrar sessão</button><button className="danger" onClick={cancel}>Cancelar</button></div></> : <div className="focus-start"><label>Meta ou projeto<input value={project} placeholder="Ex.: Portal Manutenção" onChange={event => setProject(event.target.value)} /></label><label>Relacionar à Caverna<select value={challengeId} onChange={event => setChallengeId(event.target.value)}><option value="">Nenhuma</option>{challenges.map(challenge => <option key={challenge.id} value={challenge.id}>{challenge.name}</option>)}</select></label><label>Meta<select value={goalId} onChange={event => setGoalId(event.target.value)}><option value="">Nenhuma</option>{goals.map(goal => <option key={goal.id} value={goal.id}>{goal.title}</option>)}</select></label><label>Hábito<select value={habitId} onChange={event => setHabitId(event.target.value)}><option value="">Nenhum</option>{habits.map(habit => <option key={habit.id} value={habit.id}>{habit.name}</option>)}</select></label><button onClick={start}>Iniciar Deep Work</button></div>}</section><section className="challenge-section"><h2>Últimas sessões</h2><div className="stack">{sessions.filter(item => item.status === 'completed').slice(0, 8).map(item => <article className="panel challenge-row" key={item.id}><div><strong>{item.project_name || 'Deep Work'}</strong><p>{new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(item.started_at))}</p></div><strong>{Math.floor(item.duration_seconds / 60)} min</strong></article>)}{!sessions.some(item => item.status === 'completed') && <div className="empty">Suas sessões concluídas aparecerão aqui.</div>}</div></section></> }
function elapsed(session: ReturnType<typeof getLocalFocusSessions>[number]) { return session.accumulated_seconds + (session.status === 'active' ? Math.max(0, Math.floor((Date.now() - new Date(session.started_at).getTime()) / 1000)) : 0) }
function formatSeconds(total: number) { return [Math.floor(total / 3600), Math.floor(total % 3600 / 60), total % 60].map(value => String(value).padStart(2, '0')).join(':') }
