import { chromium } from 'playwright'
import assert from 'node:assert/strict'

function samplePdf() {
  const stream = 'BT /F1 20 Tf 50 750 Td (Cavern test) Tj ET\n'
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${Buffer.byteLength(stream)} >>\nstream\n${stream}endstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ]
  let data = '%PDF-1.4\n'
  const offsets = [0]
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(data))
    data += `${index + 1} 0 obj\n${object}\nendobj\n`
  })
  const xref = Buffer.byteLength(data)
  data += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  data += offsets.slice(1).map(offset => `${String(offset).padStart(10, '0')} 00000 n \n`).join('')
  data += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`
  return Buffer.from(data)
}

const browser = await chromium.launch({
  channel: 'msedge',
  headless: true,
})
const context = await browser.newContext({ viewport: { width: 390, height: 844 } })
const page = await context.newPage()
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://127.0.0.1:5173/')
await page.getByRole('heading', { name: 'Seu dia, no seu ritmo' }).waitFor()
assert(await page.locator('.progress-empty').isVisible(), 'Estado vazio do progresso não apareceu no mobile')
await page.getByRole('link', { name: 'Criar primeiro hábito' }).first().click()
await page.locator('.habit-create-form input').first().fill('Caminhar 20 minutos')
await page.getByRole('button', { name: 'Criar hábito' }).click()
await page.getByRole('heading', { name: 'Caminhar 20 minutos' }).waitFor()
await page.goto('http://127.0.0.1:5173/')
await page.getByRole('button', { name: 'Concluir Caminhar 20 minutos' }).click()
await page.getByRole('button', { name: 'Desfazer conclusão de Caminhar 20 minutos' }).waitFor()
await page.getByRole('button', { name: 'Desfazer conclusão de Caminhar 20 minutos' }).click()
await page.getByRole('button', { name: 'Concluir Caminhar 20 minutos' }).waitFor()
await page.getByRole('button', { name: 'Concluir Caminhar 20 minutos' }).click()
console.log('daily flow', await page.locator('.today-heading p:last-child').textContent())
assert.equal(await page.locator('.progress-details-toggle').getAttribute('aria-expanded'), 'true', 'Histórico de progresso não abriu no mobile')
assert(await page.locator('#progress-history-content .activity-chart').isVisible(), 'Gráfico de progresso não apareceu no mobile')
assert(await page.locator('#progress-history-content .calendar').evaluate(element => element.scrollWidth <= element.clientWidth), 'Calendário ficou cortado no mobile')
assert(await page.locator('#progress-history-content .calendar-grid').evaluate(element => element.scrollWidth <= element.clientWidth), 'Grade do calendário excedeu o card no mobile')
assert(await page.locator('#progress-history-content .calendar').evaluate(element => element.getBoundingClientRect().right <= window.innerWidth), 'Colunas de sexta a domingo ficaram fora da tela')
await page.getByRole('button', { name: 'Ocultar histórico e estatísticas' }).click()
assert.equal(await page.locator('.progress-details-toggle').getAttribute('aria-expanded'), 'false', 'Histórico de progresso não recolheu no mobile')
await page.getByRole('button', { name: 'Ver histórico e estatísticas' }).click()
assert(await page.locator('#progress-history-content .activity-chart').isVisible(), 'Gráfico de progresso não reapareceu no mobile')
console.log('mobile progress history', true)
await page.goto('http://127.0.0.1:5173/goals')
await page.locator('form input').first().fill('Caminhar em 7 dias')
const targetInput = page.locator('.number-stepper input').first()
await targetInput.fill('0')
await page.getByRole('button', { name: 'Criar meta' }).click()
assert.equal(await page.locator('.goal-card').count(), 0, 'Invalid zero target created a goal')
assert.equal(await targetInput.getAttribute('aria-invalid'), 'true', 'Invalid target lacks feedback')
await page.getByRole('button', { name: 'Aumentar Alvo' }).click()
assert.equal(await targetInput.inputValue(), '1', 'Increment from invalid zero did not reach minimum')
await targetInput.fill('12')
assert.equal(await targetInput.inputValue(), '12', 'Target input cannot be replaced')
await page.getByRole('button', { name: 'Diminuir Alvo' }).click()
assert.equal(await targetInput.inputValue(), '11', 'Target decrement did not update')
await targetInput.fill('7')
await page.getByRole('button', { name: 'Criar meta' }).click()
console.log('goal', await page.locator('.goal-card').first().textContent())
assert(await page.locator('.goal-card').first().getByRole('button', { name: 'Concluir', exact: true }).isDisabled(), 'Goal completed before reaching target')
await page.locator('.goal-card').first().getByRole('button', { name: 'Editar meta' }).click()
const goalLink = page.locator('.goal-card').first().locator('input[type="checkbox"]').first()
assert(await goalLink.isChecked(), 'New habit was not linked to goal')
await goalLink.uncheck()
await page.locator('.goal-card').first().getByRole('button', { name: 'Descartar alterações' }).click()
await page.locator('.goal-card').first().getByRole('button', { name: 'Editar meta' }).click()
assert(await page.locator('.goal-card').first().locator('input[type="checkbox"]').first().isChecked(), 'Discarding goal edit changed its links')
await page.locator('.goal-card').first().getByRole('button', { name: 'Descartar alterações' }).click()
for (const route of ['/habits', '/goals', '/focus', '/gym', '/books', '/finance', '/checkins', '/cavern', '/achievements', '/shop', '/profile']) {
  await page.goto(`http://127.0.0.1:5173${route}`)
  const fits = await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth)
  assert(fits, `Rolagem horizontal em ${route}`)
  const unnamed = await page.locator('input:not([type="hidden"]), select, textarea, button').evaluateAll(elements => elements.filter(element => {
    const ownLabel = element.getAttribute('aria-label') || element.getAttribute('aria-labelledby') || element.getAttribute('title')
    const associated = 'labels' in element && element.labels?.length
    const text = element.tagName === 'BUTTON' ? element.textContent?.trim() : ''
    return !ownLabel && !associated && !text
  }).map(element => `${element.tagName.toLowerCase()}${element.className ? '.' + String(element.className).replaceAll(' ', '.') : ''}`))
  if (unnamed.length) console.log('unlabeled controls', route, unnamed)
  console.log(route, await page.locator('h1').first().textContent(), fits)
}
await page.goto('http://127.0.0.1:5173/shop')
await page.locator('.shop-item').first().waitFor()
assert.equal(await page.locator('.shop-item').count(), 21, 'Shop catalog is incomplete')
await page.getByRole('button', { name: 'Fogueiras' }).click()
assert.equal(await page.locator('.shop-item').count(), 6, 'Shop category filter failed')
assert(await page.getByRole('heading', { name: 'Chama Esmeralda' }).count(), 'New flame is missing')
await page.evaluate(() => {
  const key = 'cavern.local.reward-transactions.v1'
  const rewards = JSON.parse(localStorage.getItem(key) || '[]')
  rewards.push({ id: 'smoke-bonus', source_type: 'smoke', source_id: 'shop', xp: 0, embers: 1000, title: 'Teste isolado', created_at: new Date().toISOString() })
  localStorage.setItem(key, JSON.stringify(rewards))
  window.dispatchEvent(new Event('cavern:data-changed'))
})
const greenFire = page.locator('.shop-item').filter({ hasText: 'Chama Esmeralda' })
await greenFire.getByRole('button', { name: 'Comprar' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Comprar' }).click()
await greenFire.getByRole('button', { name: 'Equipar' }).click()
assert.equal(await page.locator('.shop-loadout-scene .scene-fire path').first().getAttribute('fill'), '#29b878', 'Bought flame was not applied to preview')
await page.getByRole('button', { name: 'Roupas' }).click()
assert.equal(await page.locator('.shop-item').count(), 2, 'Body items filter failed')
console.log('shop catalog and filters', true)
await page.goto('http://127.0.0.1:5173/checkins')
await page.getByRole('button', { name: 'Salvar check-in' }).click()
await page.getByText('Seu dia foi registrado.').waitFor()
console.log('checkin saved')
await page.goto('http://127.0.0.1:5173/focus')
await page.getByRole('button', { name: 'Iniciar foco' }).click()
await page.getByRole('button', { name: 'Encerrar sessão' }).click()
await page.getByText('Sessões com menos de 5 minutos não entram no histórico.').waitFor()
assert.equal(await page.locator('.challenge-row').count(), 0, 'Sessão de foco curta entrou no histórico')
console.log('short focus rejected')
await page.goto('http://127.0.0.1:5173/finance')
await page.route('https://api.coingecko.com/**', route => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ bitcoin: { brl: 500000, usd: 100000, brl_24h_change: 0 } }) }))
await page.locator('.finance-layout form').first().locator('input[type="number"]').first().fill('15')
await page.getByRole('button', { name: 'Salvar lançamento' }).click()
console.log('finance', await page.locator('.transaction').count())
await page.locator('.finance-layout form').first().locator('input[type="number"]').first().fill('0')
await page.getByRole('button', { name: 'Salvar lançamento' }).click()
assert.equal(await page.locator('.transaction').count(), 1, 'Zero-value transaction was recorded')
const financeGoalForm = page.locator('.finance-layout form').nth(1)
await financeGoalForm.locator('input').first().fill('Reserva de teste')
await financeGoalForm.locator('.number-stepper input').fill('0')
await financeGoalForm.getByRole('button', { name: 'Criar meta financeira' }).click()
assert.equal(await page.locator('.finance-goal').count(), 0, 'Zero-target financial goal was created')
await financeGoalForm.locator('.number-stepper input').fill('1500')
await financeGoalForm.getByRole('button', { name: 'Criar meta financeira' }).click()
await page.getByRole('heading', { name: 'Reserva de teste' }).waitFor()
const transactionForm = page.locator('.finance-layout form').first()
await transactionForm.locator('select').first().selectOption('buy_btc')
await transactionForm.locator('input[type="number"]').first().fill('1000')
await transactionForm.locator('input[type="number"]').nth(1).fill('1')
await transactionForm.locator('details summary').click()
await transactionForm.locator('input[type="date"]').fill('2026-09-10')
await transactionForm.getByRole('button', { name: 'Salvar lançamento' }).click()
await transactionForm.locator('select').first().selectOption('sell_btc')
await transactionForm.locator('input[type="number"]').first().fill('600')
await transactionForm.locator('input[type="number"]').nth(1).fill('0.5')
await transactionForm.locator('input[type="date"]').fill('2026-09-20')
await transactionForm.getByRole('button', { name: 'Salvar lançamento' }).click()
assert.equal(await page.locator('.transaction').count(), 3, 'BTC buy and sale did not save')
await transactionForm.locator('input[type="number"]').first().fill('700')
await transactionForm.locator('input[type="number"]').nth(1).fill('0.6')
await transactionForm.locator('input[type="date"]').fill('2026-09-15')
await transactionForm.getByRole('button', { name: 'Salvar lançamento' }).click()
assert.equal(await page.locator('.transaction').count(), 3, 'Backdated BTC sale overdrew later holdings')
await page.locator('.transaction').filter({ hasText: 'Compra de BTC' }).getByRole('button', { name: 'Excluir' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
assert.equal(await page.locator('.transaction').count(), 3, 'Deleting BTC buy left an invalid negative position')
await page.goto('http://127.0.0.1:5173/gym')
await page.getByRole('button', { name: 'Fui à academia' }).click()
console.log('gym attendance', await page.getByRole('button', { name: 'Fui à academia' }).getAttribute('class'))
await page.goto('http://127.0.0.1:5173/goals')
await page.locator('form input').first().fill('Treinar na semana')
await page.locator('form select').first().selectOption('workouts')
await page.getByRole('button', { name: 'Criar meta' }).click()
console.log('workout goal', await page.locator('.goal-card').first().locator('strong').first().textContent())
await page.goto('http://127.0.0.1:5173/cavern')
await page.getByRole('button', { name: 'Gerar para mim' }).click()
await page.locator('.challenge-editor input').first().fill('Ciclo de teste')
await page.getByRole('button', { name: 'Salvar e iniciar' }).click()
await page.getByRole('heading', { name: 'Ciclo de teste', level: 2 }).waitFor()
console.log('cavern started', await page.locator('.active-cavern').count())
assert(await page.getByRole('button', { name: 'Concluir Caverna' }).isDisabled(), 'Caverna pode ser concluída antes do prazo')
console.log('cavern completion locked', true)
await page.reload()
await page.getByRole('heading', { name: 'Ciclo de teste', level: 2 }).waitFor()
console.log('persistence', 'cavern and habits retained')
await page.setViewportSize({ width: 1280, height: 800 })
await page.goto('http://127.0.0.1:5173/')
assert(await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth), 'Rolagem horizontal no desktop')
console.log('desktop fits viewport', true)
await page.locator('.nav-more summary').click()
await page.locator('.nav-more').getByRole('link', { name: 'Livros' }).click()
await page.getByRole('heading', { name: 'Minha Biblioteca' }).waitFor()
console.log('desktop navigation', await page.locator('h1').first().textContent())
await page.locator('.book-import input[type="file"]').setInputFiles({ name: 'Teste.pdf', mimeType: 'application/pdf', buffer: samplePdf() })
await page.getByText('Livro adicionado à biblioteca.').waitFor()
await page.getByRole('link', { name: 'Ler agora' }).click()
await page.locator('.reader').waitFor()
await page.locator('canvas').first().waitFor({ timeout: 10000 })
assert(await page.locator('canvas').count() > 0, 'Leitor de PDF não renderizou')
console.log('pdf reader', await page.locator('canvas').count())
await page.setViewportSize({ width: 320, height: 780 })
assert(await page.evaluate(() => Math.max(document.body.scrollWidth, document.documentElement.scrollWidth) <= window.innerWidth), 'PDF reader overflows at 320px')
await page.setViewportSize({ width: 1280, height: 800 })
await page.goto('http://127.0.0.1:5173/books')
assert((await page.locator('.book-card').first().textContent()).includes('LENDO'), 'Opened book did not switch to reading')
assert((await page.locator('.book-card').first().textContent()).includes('0%'), 'Single-page PDF showed 100% before reading')
await page.getByRole('link', { name: 'Ler agora' }).click()
await page.getByRole('button', { name: 'Concluir leitura' }).click()
await page.goto('http://127.0.0.1:5173/books')
await page.locator('.book-card').first().waitFor()
await page.locator('.book-card').first().getByText('100%').waitFor()
assert((await page.locator('.book-card').first().textContent()).includes('100%'), 'Single-page PDF cannot be completed')
await page.evaluate(() => {
  const key = 'cavern.local.books.v1'
  const books = JSON.parse(localStorage.getItem(key) || '[]')
  books[0].status = 'reading'
  localStorage.setItem(key, JSON.stringify(books))
})
await page.reload()
await page.locator('.book-card').first().getByText('LENDO').waitFor()
await page.evaluate(() => {
  const key = 'cavern.local.books.v1'
  const books = JSON.parse(localStorage.getItem(key) || '[]')
  books[0].status = 'finished'
  localStorage.setItem(key, JSON.stringify(books))
})
await page.reload()
await page.locator('.book-card').first().getByText('100%').waitFor()
await page.locator('.book-card').first().getByRole('button', { name: 'Excluir' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
await page.locator('.book-card').first().waitFor({ state: 'detached' })
assert.equal(await page.locator('.book-card').count(), 0, 'Deleted book remained in library')
assert.equal(await page.evaluate(() => JSON.parse(localStorage.getItem('cavern.local.reading-sessions.v1') || '[]').length), 0, 'Deleting book retained reading sessions')
await page.setViewportSize({ width: 390, height: 844 })
await page.goto('http://127.0.0.1:5173/')
await page.getByRole('button', { name: 'Abrir menu principal' }).click()
await page.locator('.nav-more summary').click()
await page.locator('.nav-more').getByRole('link', { name: 'Financeiro' }).click()
await page.getByRole('heading', { name: 'Financeiro' }).waitFor()
console.log('mobile navigation', await page.getByRole('button', { name: 'Abrir menu principal' }).getAttribute('aria-expanded'))
await page.goto('http://127.0.0.1:5173/cavern')
await page.locator('.active-cavern').waitFor()
await page.evaluate(() => {
  const key = 'cavern.local.challenges.v1'
  const challenges = JSON.parse(localStorage.getItem(key) || '[]')
  const target = challenges.find(challenge => challenge.name === 'Ciclo de teste')
  target.startDate = '2020-01-01'
  target.endDate = '2020-01-01'
  target.durationDays = 1
  localStorage.setItem(key, JSON.stringify(challenges))
  window.dispatchEvent(new Event('cavern:data-changed'))
})
await page.reload()
await page.getByRole('button', { name: 'Encerrar sem concluir' }).waitFor()
assert.equal(await page.getByRole('button', { name: 'Concluir Caverna' }).count(), 0, 'Caverna com progresso insuficiente pode ser concluída')
await page.getByRole('button', { name: 'Encerrar sem concluir' }).click()
await page.locator('.active-cavern').waitFor({ state: 'detached' })
assert(!await page.evaluate(() => JSON.parse(localStorage.getItem('cavern.local.reward-transactions.v1') || '[]').some(reward => reward.source_type === 'challenge')), 'Caverna falha concedeu recompensa')
console.log('low-score cavern rejected')
await page.locator('.challenge-row').filter({ hasText: 'Ciclo de teste' }).getByRole('button', { name: 'Excluir' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
await page.getByRole('heading', { name: 'Ciclo de teste' }).waitFor({ state: 'detached' })
const goalIdToDelete = await page.evaluate(() => JSON.parse(localStorage.getItem('cavern.local.goals.v2') || '[]').find(goal => goal.title === 'Caminhar em 7 dias')?.id)
await page.goto('http://127.0.0.1:5173/goals')
await page.getByRole('button', { name: 'Excluir meta Caminhar em 7 dias' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
await page.getByRole('heading', { name: 'Caminhar em 7 dias' }).waitFor({ state: 'detached' })
assert(!await page.evaluate(goalId => JSON.parse(localStorage.getItem('cavern.local.goal-habit-links.v1') || '[]').some(link => link.goal_id === goalId), goalIdToDelete), 'Deleting goal retained habit links')
await page.locator('form').first().locator('input').first().fill('Meta manual de teste')
await page.locator('form').first().locator('select').first().selectOption('custom')
await page.locator('form').first().locator('.number-stepper input').fill('3')
await page.getByRole('button', { name: 'Criar meta' }).click()
const manualGoal = page.locator('.goal-card').filter({ hasText: 'Meta manual de teste' })
await manualGoal.getByRole('spinbutton', { name: 'Progresso manual' }).fill('3')
await manualGoal.getByRole('button', { name: 'Editar meta' }).click()
await manualGoal.locator('.goal-edit-form .number-stepper input').fill('2')
await manualGoal.getByRole('button', { name: 'Salvar alterações' }).click()
assert.equal(await manualGoal.getByRole('spinbutton', { name: 'Progresso manual' }).inputValue(), '2', 'Lowering target left manual progress above maximum')
await manualGoal.getByRole('button', { name: 'Concluir', exact: true }).click()
const manualGoalId = await page.evaluate(() => JSON.parse(localStorage.getItem('cavern.local.goals.v2') || '[]').find(goal => goal.title === 'Meta manual de teste')?.id)
assert(await page.evaluate(goalId => JSON.parse(localStorage.getItem('cavern.local.reward-transactions.v1') || '[]').some(reward => reward.source_type === 'goal' && reward.source_id === goalId), manualGoalId), 'Completing goal did not grant reward')
await manualGoal.getByRole('button', { name: 'Excluir meta Meta manual de teste' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
assert(!await page.evaluate(goalId => JSON.parse(localStorage.getItem('cavern.local.reward-transactions.v1') || '[]').some(reward => reward.source_type === 'goal' && reward.source_id === goalId), manualGoalId), 'Deleting goal retained its reward')
const habitIdToDelete = await page.evaluate(() => JSON.parse(localStorage.getItem('cavern.local.habits.v1') || '[]').find(habit => habit.name === 'Caminhar 20 minutos')?.id)
await page.goto('http://127.0.0.1:5173/habits')
await page.locator('.habit-card').filter({ hasText: 'Caminhar 20 minutos' }).locator('summary').click()
await page.locator('.habit-card').filter({ hasText: 'Caminhar 20 minutos' }).getByRole('button', { name: 'Excluir' }).click()
await page.locator('.confirm-dialog').getByRole('button', { name: 'Excluir' }).click()
await page.getByRole('heading', { name: 'Caminhar 20 minutos' }).waitFor({ state: 'detached' })
assert(!await page.evaluate(habitId => JSON.parse(localStorage.getItem('cavern.local.goal-habit-links.v1') || '[]').some(link => link.habit_id === habitId), habitIdToDelete), 'Deleting habit retained goal links')
assert(!await page.evaluate(habitId => JSON.parse(localStorage.getItem('cavern.local.reward-transactions.v1') || '[]').some(reward => reward.source_type === 'habit' && reward.source_id.startsWith(`${habitId}:`)), habitIdToDelete), 'Deleting habit retained its reward')
console.log('pageerrors', errors)
assert.equal(errors.length, 0, 'Erros JavaScript no navegador')
for (const width of [320, 360, 430]) {
  await page.setViewportSize({ width, height: 780 })
  for (const route of ['/', '/goals', '/habits', '/finance', '/gym', '/cavern', '/shop', '/checkins', '/books', '/focus', '/profile']) {
    await page.goto(`http://127.0.0.1:5173${route}`)
    await page.locator('h1').first().waitFor()
    assert(await page.evaluate(() => Math.max(document.body.scrollWidth, document.documentElement.scrollWidth) <= window.innerWidth), `Horizontal overflow at ${width}px on ${route}`)
  }
}
const topbarBeforeInset = await page.locator('.mobile-topbar').evaluate(element => element.getBoundingClientRect().height)
await page.evaluate(() => document.documentElement.style.setProperty('--safe-area-inset-top', '24px'))
const topbarAfterInset = await page.locator('.mobile-topbar').evaluate(element => element.getBoundingClientRect().height)
assert(topbarAfterInset >= topbarBeforeInset + 20, 'Android safe-area inset did not expand mobile topbar')
console.log('mobile widths and Android safe area', true)
await browser.close()
