import { useEffect, useState } from 'react'
import { getLocalAchievements, grantLocalReward, unlockLocalAchievement } from '../../lib/local-store'
import { useLocalRevision } from '../../lib/use-local-revision'
import { achievements, type Achievement } from './domain/achievement'
import { evaluateAchievements, formatAchievementProgress } from './services/achievement.service'
import './achievements.css'

export function AchievementsPage() {
  useLocalRevision(); const [selected, setSelected] = useState<Achievement | null>(null)
  useEffect(() => { evaluateAchievements().forEach(item => { if (unlockLocalAchievement(item.id)) grantLocalReward('achievement', item.id, item.rewardXp, item.rewardEmbers, item.title) }) }, [])
  const unlocked = new Set(getLocalAchievements().map(item => item.id)); const secret = achievements.find(item => item.hidden); const regular = achievements.filter(item => !item.hidden); const platinum = unlocked.size === achievements.length
  return <><header><p className="eyebrow">CONQUISTAS</p><h1>Badges</h1><p>Disciplina real desbloqueia marcas permanentes da sua jornada.</p></header><section className={`platinum-marker ${platinum ? 'complete' : ''}`}><span>{platinum ? '🏆' : '◇'}</span><div><p className="eyebrow">PLATINA DA CAVERNA</p><h2>{unlocked.size} / {achievements.length} conquistas</h2><p>{platinum ? 'Você dominou todos os marcos da Caverna.' : 'Desbloqueie todas as conquistas para alcançar a Platina.'}</p></div><div className="progress-track"><i style={{ width: `${unlocked.size / achievements.length * 100}%` }} /></div></section><section className="shop-grid">{regular.map(item => <AchievementCard item={item} unlocked={unlocked.has(item.id)} onOpen={() => setSelected(item)} key={item.id} />)}</section>{secret && <section className="secret-achievement-wrap"><AchievementCard item={secret} unlocked={unlocked.has(secret.id)} secret onOpen={() => setSelected(secret)} /></section>}<AchievementDialog achievement={selected} unlocked={selected ? unlocked.has(selected.id) : false} onClose={() => setSelected(null)} /></>
}
function AchievementCard({ item, unlocked, secret = false, onOpen }: { item: Achievement; unlocked: boolean; secret?: boolean; onOpen: () => void }) { return <button className={`panel shop-item achievement-card ${unlocked ? 'achievement-unlocked' : ''} ${secret ? 'secret-achievement' : ''}`} onClick={onOpen}><strong>{unlocked ? item.icon : secret ? '🏆' : '???'}</strong><p className="eyebrow">{unlocked ? 'DESBLOQUEADA' : 'EM PROGRESSO'}</p><h2>{unlocked ? item.title : item.hidden ? 'Conquista secreta' : item.title}</h2><p>{unlocked ? item.description : item.hidden ? item.progressLabel : formatAchievementProgress(item.condition)}</p><b>+{item.rewardXp} XP · +{item.rewardEmbers} Brasas</b></button> }
function AchievementDialog({ achievement, unlocked, onClose }: { achievement: Achievement | null; unlocked: boolean; onClose: () => void }) { if (!achievement) return null; return <div className="dialog-backdrop" onMouseDown={onClose}><section className="confirm-dialog achievement-dialog" role="dialog" aria-modal="true" onMouseDown={event => event.stopPropagation()}><p className="eyebrow">{achievement.category} · {achievement.rarity}</p><strong>{unlocked ? achievement.icon : '🏆'}</strong><h2>{unlocked ? achievement.title : achievement.hidden ? 'Conquista secreta' : achievement.title}</h2><p>{achievement.description}</p><div className="achievement-requirement"><span>Para desbloquear</span><b>{achievement.hidden ? 'Alcance 7 Dias Perfeitos na mesma Caverna.' : achievement.progressLabel}</b><strong>{achievement.hidden ? '???' : formatAchievementProgress(achievement.condition)}</strong></div><p className="achievement-reward">+{achievement.rewardXp} XP · +{achievement.rewardEmbers} Brasas</p><button onClick={onClose}>Fechar</button></section></div> }
