import { useState } from 'react'
import type { FormEvent } from 'react'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { NumberStepper } from '../components/NumberStepper'
import { addLocalGoal, deleteLocalGoal, getGoalHabitIds, getHabitGoalIds, getLocalGoals, getLocalHabits, goalProgress, setHabitGoalLinks, today, updateLocalGoal, type GoalMetric, type GoalPeriod, type LocalGoal } from '../lib/local-store'

const metrics: { value: GoalMetric; label: string; unit: string }[] = [{ value: 'habit_days', label: 'Dias de hábito', unit: 'dias' }, { value: 'pages_read', label: 'Páginas lidas', unit: 'páginas' }, { value: 'reading_minutes', label: 'Minutos de leitura', unit: 'minutos' }, { value: 'study_minutes', label: 'Minutos de estudo', unit: 'minutos' }, { value: 'workouts', label: 'Treinos', unit: 'treinos' }, { value: 'custom', label: 'Personalizada', unit: 'unidades' }]

export function Goals() {
  const [goals, setGoals] = useState(getLocalGoals); const [title, setTitle] = useState(''); const [target, setTarget] = useState(20); const [metric, setMetric] = useState<GoalMetric>('habit_days'); const [period, setPeriod] = useState<GoalPeriod>('daily'); const [startDate, setStartDate] = useState(today()); const [endDate, setEndDate] = useState(today()); const [message, setMessage] = useState(''); const [deleting, setDeleting] = useState<LocalGoal | null>(null)
  const metricInfo = metrics.find(item => item.value === metric)!
  function create(event: FormEvent) { event.preventDefault(); if (!title.trim() || target <= 0 || endDate < startDate) return; const created = title.trim(); setGoals(addLocalGoal({ title: created, target_value: target, unit: metricInfo.unit, metric, period_type: period, start_date: startDate, end_date: endDate })); setTitle(''); setMessage('Meta criada e hábitos compatíveis foram vinculados automaticamente.') }
  function update(id: string, changes: Partial<LocalGoal>) { setGoals(updateLocalGoal(id, changes)); setMessage('Meta atualizada.') }
  function remove() { if (!deleting) return; setGoals(deleteLocalGoal(deleting.id)); setMessage(`Meta “${deleting.title}” removida.`); setDeleting(null) }
  return <><header><p className="eyebrow">DIREÇÃO</p><h1>Metas</h1><p>Defina um alvo e escolha — ou deixe o sistema sugerir — os hábitos que o fazem avançar.</p></header>{message && <p className="action-feedback" role="status">{message}</p>}<section className="two-columns"><form className="panel form" onSubmit={create}><h2>Nova meta</h2><label>Título<input required value={title} placeholder="Ler com consistência" onChange={event => setTitle(event.target.value)} /></label><label>Métrica<select value={metric} onChange={event => setMetric(event.target.value as GoalMetric)}>{metrics.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><div className="date-pair"><NumberStepper label="Alvo" value={target} min={1} onChange={setTarget} suffix={metricInfo.unit} /><label>Período<select value={period} onChange={event => setPeriod(event.target.value as GoalPeriod)}><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="total">Total</option></select></label></div><div className="date-pair"><label>Início<input required type="date" value={startDate} onChange={event => setStartDate(event.target.value)} /></label><label>Fim<input required min={startDate} type="date" value={endDate} onChange={event => setEndDate(event.target.value)} /></label></div><button>Criar meta</button></form><section>{goals.length === 0 ? <div className="empty">Defina uma meta para dar direção às suas ações.</div> : <div className="stack">{goals.map(goal => <GoalCard goal={goal} onUpdate={update} onDelete={() => setDeleting(goal)} key={goal.id} />)}</div>}</section></section><ConfirmDialog open={Boolean(deleting)} title="Excluir esta meta?" description={`A meta “${deleting?.title ?? ''}” e seus vínculos com hábitos serão removidos.`} onCancel={() => setDeleting(null)} onConfirm={remove} /></>
}

function GoalCard({ goal, onUpdate, onDelete }: { goal: LocalGoal; onUpdate: (id: string, changes: Partial<LocalGoal>) => void; onDelete: () => void }) {
  const [editing, setEditing] = useState(false); const habits = getLocalHabits().filter(habit => habit.active); const [habitIds, setHabitIds] = useState(() => getGoalHabitIds(goal.id)); const progress = goalProgress(goal); const percent = Math.min(100, Math.round((progress / goal.target_value) * 100)); const linkedHabits = habits.filter(habit => habitIds.includes(habit.id))
  function toggleHabit(habitId: string, checked: boolean) { const next = checked ? [...habitIds, habitId] : habitIds.filter(id => id !== habitId); setHabitIds(next); const currentGoals = getHabitGoalIds(habitId); setHabitGoalLinks(habitId, checked ? [...new Set([...currentGoals, goal.id])] : currentGoals.filter(id => id !== goal.id)) }
  return <article className="panel goal-card"><div className="card-heading"><div><p className="eyebrow">{goal.status} · {labelForPeriod(goal.period_type)}</p><h2>{goal.title}</h2></div><button className="danger icon-button" onClick={onDelete} aria-label="Excluir meta">×</button></div><strong>{progress} <span>/ {goal.target_value} {goal.unit}</span></strong><div className="progress-track"><i style={{ width: `${percent}%` }} /></div><small>{percent}% concluído</small><p className="linked-habits"><b>Hábitos vinculados:</b> {linkedHabits.length ? linkedHabits.map(habit => habit.name).join(', ') : 'nenhum — clique em editar para escolher.'}</p>{editing && <><div className="goal-edit"><label>Título<input value={goal.title} onChange={event => onUpdate(goal.id, { title: event.target.value })} /></label><NumberStepper label="Alvo" value={goal.target_value} min={1} onChange={value => onUpdate(goal.id, { target_value: value })} suffix={goal.unit} /><label>Período<select value={goal.period_type} onChange={event => onUpdate(goal.id, { period_type: event.target.value as GoalPeriod })}><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="total">Total</option></select></label></div><fieldset className="goal-selector"><legend>Escolha os hábitos ligados a esta meta</legend>{habits.length ? habits.map(habit => <label key={habit.id}><input type="checkbox" checked={habitIds.includes(habit.id)} onChange={event => toggleHabit(habit.id, event.target.checked)} /> {habit.name}</label>) : <p>Crie um hábito primeiro.</p>}</fieldset></>}{goal.metric === 'custom' && goal.status === 'active' && <NumberStepper label="Progresso manual" value={goal.manual_progress} min={0} max={goal.target_value} onChange={value => onUpdate(goal.id, { manual_progress: value })} suffix={goal.unit} />}<div className="habit-actions"><button className="subtle" onClick={() => setEditing(!editing)}>{editing ? 'Fechar edição' : 'Editar e vincular hábitos'}</button>{goal.status === 'active' && <button onClick={() => onUpdate(goal.id, { status: 'completed' })}>Concluir</button>}{goal.status === 'active' && <button className="subtle" onClick={() => onUpdate(goal.id, { status: 'cancelled' })}>Cancelar</button>}{goal.status !== 'active' && <button className="subtle" onClick={() => onUpdate(goal.id, { status: 'active' })}>Reativar</button>}</div></article>
}
function labelForPeriod(value: GoalPeriod) { return ({ daily: 'diária', weekly: 'semanal', monthly: 'mensal', total: 'total' })[value] }
