import { useState } from 'react'
import type { FormEvent } from 'react'
import { addLocalGoal, deleteLocalGoal, getLocalCaverns, getLocalGoals, goalProgress, today, updateLocalGoal, type GoalMetric, type GoalPeriod, type LocalGoal } from '../lib/local-store'

const metrics: { value: GoalMetric; label: string; unit: string }[] = [{ value: 'habit_days', label: 'Dias de hábito', unit: 'dias' }, { value: 'pages_read', label: 'Páginas lidas', unit: 'páginas' }, { value: 'reading_minutes', label: 'Minutos de leitura', unit: 'minutos' }, { value: 'study_minutes', label: 'Minutos de estudo', unit: 'minutos' }, { value: 'workouts', label: 'Treinos', unit: 'treinos' }, { value: 'custom', label: 'Personalizada', unit: 'unidades' }]

export function Goals() {
  const [goals, setGoals] = useState(getLocalGoals)
  const caverns = getLocalCaverns()
  const [title, setTitle] = useState('')
  const [target, setTarget] = useState('20')
  const [metric, setMetric] = useState<GoalMetric>('habit_days')
  const [period, setPeriod] = useState<GoalPeriod>('daily')
  const [cavernId, setCavernId] = useState('')
  const [startDate, setStartDate] = useState(today())
  const [endDate, setEndDate] = useState(today())
  const [message, setMessage] = useState('')
  const metricInfo = metrics.find(item => item.value === metric)!
  function create(event: FormEvent) { event.preventDefault(); const value = Number(target); if (!title.trim() || !Number.isFinite(value) || value <= 0 || endDate < startDate) return; const created = title.trim(); setGoals(addLocalGoal({ title: created, target_value: value, unit: metricInfo.unit, metric, period_type: period, cavern_id: cavernId || null, start_date: startDate, end_date: endDate })); setTitle(''); setMessage(`Meta “${created}” criada. Os registros vão atualizar seu progresso.`) }
  function update(id: string, changes: Partial<LocalGoal>) { setGoals(updateLocalGoal(id, changes)); setMessage(changes.status === 'completed' ? 'Meta marcada como concluída.' : changes.status === 'cancelled' ? 'Meta cancelada. Você pode reativá-la depois.' : 'Meta atualizada.') }
  return <><header><p className="eyebrow">DIREÇÃO</p><h1>Metas</h1><p>Defina um alvo mensurável para saber no que focar; o progresso é calculado pelos seus registros, não por estimativa.</p></header>{message && <p className="action-feedback" role="status">{message}</p>}<section className="two-columns"><form className="panel form" onSubmit={create}><h2>Nova meta</h2><label>Título<input required value={title} placeholder="Ler com consistência" onChange={event => setTitle(event.target.value)} /></label><label>Métrica<select value={metric} onChange={event => setMetric(event.target.value as GoalMetric)}>{metrics.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><div className="date-pair"><label>Alvo<input required min="1" type="number" value={target} onChange={event => setTarget(event.target.value)} /></label><label>Período<select value={period} onChange={event => setPeriod(event.target.value as GoalPeriod)}><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="total">Total</option></select></label></div><label>Caverna<select value={cavernId} onChange={event => setCavernId(event.target.value)}><option value="">Sem Caverna</option>{caverns.map(cavern => <option value={cavern.id} key={cavern.id}>{cavern.name}</option>)}</select></label><div className="date-pair"><label>Início<input required type="date" value={startDate} onChange={event => setStartDate(event.target.value)} /></label><label>Fim<input required min={startDate} type="date" value={endDate} onChange={event => setEndDate(event.target.value)} /></label></div><button>Criar meta</button></form><section>{goals.length === 0 ? <div className="empty">Defina uma meta para dar direção à sua próxima Caverna.</div> : <div className="stack">{goals.map(goal => <GoalCard goal={goal} onUpdate={update} onDelete={() => { if (window.confirm(`Excluir a meta “${goal.title}”?`)) { setGoals(deleteLocalGoal(goal.id)); setMessage(`Meta “${goal.title}” removida.`) } }} key={goal.id} />)}</div>}</section></section></>
}

function GoalCard({ goal, onUpdate, onDelete }: { goal: LocalGoal; onUpdate: (id: string, changes: Partial<LocalGoal>) => void; onDelete: () => void }) {
  const [editing, setEditing] = useState(false); const progress = goalProgress(goal); const percent = Math.min(100, Math.round((progress / goal.target_value) * 100)); const isCustom = goal.metric === 'custom'
  return <article className="panel goal-card"><div className="card-heading"><div><p className="eyebrow">{goal.status} · {labelForPeriod(goal.period_type)}</p><h2>{goal.title}</h2></div><button className="danger icon-button" onClick={onDelete} aria-label="Excluir meta">×</button></div><strong>{progress} <span>/ {goal.target_value} {goal.unit}</span></strong><div className="progress-track"><i style={{ width: `${percent}%` }} /></div><small>{percent}% concluído</small>{editing && <div className="goal-edit"><label>Título<input value={goal.title} onChange={event => onUpdate(goal.id, { title: event.target.value })} /></label><label>Alvo<input min="1" type="number" value={goal.target_value} onChange={event => onUpdate(goal.id, { target_value: Number(event.target.value) || 1 })} /></label><label>Período<select value={goal.period_type} onChange={event => onUpdate(goal.id, { period_type: event.target.value as GoalPeriod })}><option value="daily">Diário</option><option value="weekly">Semanal</option><option value="monthly">Mensal</option><option value="total">Total</option></select></label></div>}{isCustom && goal.status === 'active' && <label className="manual-progress">Progresso manual<input min="0" max={goal.target_value} type="number" value={goal.manual_progress} onChange={event => onUpdate(goal.id, { manual_progress: Number(event.target.value) || 0 })} /></label>}<div className="habit-actions"><button className="subtle" onClick={() => setEditing(!editing)}>{editing ? 'Fechar edição' : 'Editar'}</button>{goal.status === 'active' && <button onClick={() => onUpdate(goal.id, { status: 'completed' })}>Concluir</button>}{goal.status === 'active' && <button className="subtle" onClick={() => onUpdate(goal.id, { status: 'cancelled' })}>Cancelar</button>}{goal.status !== 'active' && <button className="subtle" onClick={() => onUpdate(goal.id, { status: 'active' })}>Reativar</button>}</div></article>
}

function labelForPeriod(value: GoalPeriod) { return ({ daily: 'diária', weekly: 'semanal', monthly: 'mensal', total: 'total' })[value] }
