import { useState } from 'react'
import type { FormEvent } from 'react'
import { ConfirmDialog } from '../components/ConfirmDialog'
import { addLocalHabit, deleteLocalHabit, getHabitGoalIds, getLocalGoals, getLocalHabits, habitStreak, logHabit, setHabitGoalLinks, today, updateLocalHabit, type HabitCategory, type HabitType, type LocalHabit } from '../lib/local-store'

const categories: { value: HabitCategory; label: string }[] = [{ value: 'workout', label: 'Treino' }, { value: 'study', label: 'Estudo' }, { value: 'meditation', label: 'Meditação' }, { value: 'reading', label: 'Leitura' }, { value: 'custom', label: 'Outro' }]
export function Habits() {
  const [habits, setHabits] = useState(getLocalHabits); const [name, setName] = useState(''); const [type, setType] = useState<HabitType>('positive'); const [category, setCategory] = useState<HabitCategory>('workout'); const [description, setDescription] = useState(''); const [logDate, setLogDate] = useState(today()); const [message, setMessage] = useState(''); const [goalIds, setGoalIds] = useState<string[]>([]); const [deleting, setDeleting] = useState<LocalHabit | null>(null); const goals = getLocalGoals().filter(goal => goal.status === 'active')
  function create(event: FormEvent) { event.preventDefault(); if (!name.trim()) return; const created = name.trim(); const next = addLocalHabit({ name: created, description: description.trim() || null, type, category, target_days: null, started_at: logDate }); setHabitGoalLinks(next[0].id, [...new Set([...getHabitGoalIds(next[0].id), ...goalIds])]); setHabits(next); setName(''); setDescription(''); setGoalIds([]); setMessage(`Hábito “${created}” criado.`) }
  function update(item: LocalHabit, status: 'completed' | 'failed' | 'skipped') { logHabit(item.id, logDate, status); setHabits([...getLocalHabits()]); setMessage(status === 'completed' ? `“${item.name}” marcado como concluído.` : `Registro de “${item.name}” atualizado.`) }
  function remove() { if (!deleting) return; setHabits(deleteLocalHabit(deleting.id)); setMessage(`Hábito “${deleting.name}” removido.`); setDeleting(null) }
  return <><header><p className="eyebrow">CONSISTÊNCIA</p><h1>Hábitos</h1><p>Crie práticas e conecte-as diretamente às metas que elas fazem avançar.</p></header>{message && <p className="action-feedback" role="status">{message}</p>}<section className="log-date"><div className="log-date-copy"><span>Registrar atividade em</span><strong>{formatLongDay(logDate)}</strong></div><input aria-label="Data do registro" type="date" max={today()} value={logDate} onChange={event => setLogDate(event.target.value)} /></section><section className="two-columns habits-layout"><form className="panel form habit-create-form" onSubmit={create}><div><p className="eyebrow">NOVO HÁBITO</p><h2>Comece uma prática</h2><p>Você poderá ajustar e vincular metas a qualquer momento.</p></div><label>Nome<input required value={name} placeholder="Ex.: Academia" onChange={event => setName(event.target.value)} /></label><label>Categoria<select value={category} onChange={event => setCategory(event.target.value as HabitCategory)}>{categories.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label><label>Descrição<input value={description} placeholder="Opcional" onChange={event => setDescription(event.target.value)} /></label><label>Tipo<select value={type} onChange={event => setType(event.target.value as HabitType)}><option value="positive">Hábito positivo</option><option value="abstinence">Abstinência — Sem X</option></select></label><GoalSelector goals={goals} selected={goalIds} onChange={setGoalIds} /><button>Criar hábito</button></form><section>{habits.length === 0 ? <div className="empty">Crie um hábito positivo ou um contador “Sem X”.</div> : <div className="stack habits-stack">{habits.filter(habit => habit.active).map(habit => <HabitCard habit={habit} goals={goals} logDate={logDate} onLog={update} onChange={changes => setHabits(updateLocalHabit(habit.id, changes))} onDelete={() => setDeleting(habit)} key={habit.id} />)}</div>}</section></section><ConfirmDialog open={Boolean(deleting)} title="Excluir este hábito?" description={`“${deleting?.name ?? ''}” e todos os registros associados serão apagados.`} onCancel={() => setDeleting(null)} onConfirm={remove} /></>
}
function GoalSelector({ goals, selected, onChange }: { goals: ReturnType<typeof getLocalGoals>; selected: string[]; onChange: (ids: string[]) => void }) { if (!goals.length) return <p className="linked-habits">Crie uma meta primeiro para poder vinculá-la.</p>; return <fieldset className="goal-selector"><legend>Metas vinculadas</legend>{goals.map(goal => <label key={goal.id}><input type="checkbox" checked={selected.includes(goal.id)} onChange={event => onChange(event.target.checked ? [...selected, goal.id] : selected.filter(id => id !== goal.id))} /> {goal.title}</label>)}</fieldset> }
function HabitCard({ habit, goals, logDate, onLog, onChange, onDelete }: { habit: LocalHabit; goals: ReturnType<typeof getLocalGoals>; logDate: string; onLog: (habit: LocalHabit, status: 'completed' | 'failed' | 'skipped') => void; onChange: (changes: Partial<LocalHabit>) => void; onDelete: () => void }) { const [editing, setEditing] = useState(false); const [selected, setSelected] = useState(() => getHabitGoalIds(habit.id)); const streak = habitStreak(habit.id); const category = categories.find(item => item.value === habit.category)?.label ?? 'Outro'; const linkedGoals = goals.filter(goal => selected.includes(goal.id)); function saveLinks(ids: string[]) { setSelected(ids); setHabitGoalLinks(habit.id, ids) }
  return <article className="panel habit-card"><div className="habit-card-heading"><div><p className="eyebrow">{category} · {habit.type === 'abstinence' ? 'contador sem' : 'hábito'}</p><h2>{habit.name}</h2>{habit.description && <p>{habit.description}</p>}{linkedGoals.length > 0 && <p className="linked-habits">Metas: {linkedGoals.map(goal => goal.title).join(', ')}</p>}</div><div className="habit-streak"><strong>{streak}</strong><span>dias seguidos</span></div></div>{editing && <><div className="goal-edit habit-edit"><label>Nome<input value={habit.name} onChange={event => onChange({ name: event.target.value })} /></label><label>Categoria<select value={habit.category} onChange={event => onChange({ category: event.target.value as HabitCategory })}>{categories.map(item => <option value={item.value} key={item.value}>{item.label}</option>)}</select></label></div><GoalSelector goals={goals} selected={selected} onChange={saveLinks} /></>}<div className="habit-actions"><button onClick={() => onLog(habit, 'completed')}>Concluí em {formatDay(logDate)}</button><button className="subtle" onClick={() => onLog(habit, 'failed')}>Falhei</button><button className="subtle" onClick={() => onLog(habit, 'skipped')}>Pular</button><button className="subtle" onClick={() => setEditing(!editing)}>{editing ? 'Fechar edição' : 'Editar'}</button><button className="danger" onClick={onDelete}>Excluir</button></div></article> }
function formatDay(value: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: '2-digit' }).format(new Date(`${value}T12:00:00`)) }
function formatLongDay(value: string) { return new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(`${value}T12:00:00`)) }
