import { getLocalCheckIns, getLocalHabitLogs, getLocalReadingSessions, overallStreak, today } from '../lib/local-store'
import { useLocalRevision } from '../lib/use-local-revision'

const weekdays = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom']

export function Progress() {
  useLocalRevision()
  const logs = getLocalHabitLogs(); const sessions = getLocalReadingSessions(); const checkins = getLocalCheckIns()
  const now = new Date(); const current = monthRange(now.getFullYear(), now.getMonth()); const previous = monthRange(now.getFullYear(), now.getMonth() - 1)
  const streak = overallStreak(logs); const days = recentDays(14); const active = new Set(logs.filter(log => log.status === 'completed').map(log => log.date))
  const chart = days.map(date => ({ date, amount: logs.filter(log => log.date === date && log.status === 'completed').length }))
  const metrics = [{ label: 'Dias ativos', current: uniqueCompleted(logs, current), previous: uniqueCompleted(logs, previous) }, { label: 'Páginas lidas', current: pagesIn(sessions, current), previous: pagesIn(sessions, previous) }, { label: 'Check-ins', current: countIn(checkins, current), previous: countIn(checkins, previous) }]
  return <><header><p className="eyebrow">VISÃO GERAL</p><h1>Seu progresso</h1><p>Consistência se constrói dia após dia.</p></header><FireJourney streak={streak} /><section className="visual-summary"><article className="streak-hero"><span>Sequência atual</span><strong>{streak}</strong><small>dias consecutivos</small></article><ActivityChart values={chart} /></section><MonthlyComparison metrics={metrics} /><section className="calendar-section"><div><p className="eyebrow">CALENDÁRIO</p><h2>{monthLabel()}</h2></div><Calendar activeDates={active} /></section></>
}

function FireJourney({ streak }: { streak: number }) {
  const level = streak === 0 ? 0 : Math.min(4, Math.floor((streak - 1) / 7) + 1); const next = level * 7; const labels = ['Fogueira apagada', 'Primeira chama', 'Brasa firme', 'Fogueira forte', 'Chama lendária']; const message = streak === 0 ? 'Conclua um hábito hoje para acender sua fogueira.' : level === 4 ? 'Você alcançou a chama lendária. Continue cuidando dela.' : `Faltam ${Math.max(1, next - streak)} dias para ${labels[level + 1].toLowerCase()}.`
  return <section className={`fire-journey level-${level}`}><div className="fire-copy"><p className="eyebrow">SUA FOGUEIRA</p><h2>{labels[level]}</h2><p>{message}</p><div className="fire-milestones">{[0, 7, 14, 21, 28].map(value => <span className={streak >= value ? 'reached' : ''} key={value}>{value === 0 ? 'Hoje' : `${value}d`}</span>)}</div></div><div className="camp-scene" aria-label={`Fogueira nível ${level + 1}; sequência de ${streak} dias`}><StreakScene level={level} /></div><strong className="fire-count"><span>{level === 0 ? '💨' : '🔥'}</span>{streak}<small>dias</small></strong></section>
}

function StreakScene({ level }: { level: number }) {
  const sad = level === 0; const fireScale = [0, .62, .82, 1, 1.18][level]
  return <svg className="streak-scene" viewBox="0 0 280 180" role="img" aria-label={sad ? 'Mascote triste diante de uma fogueira apagada' : 'Mascote aquecido ao lado de uma fogueira'}><ellipse cx="145" cy="158" rx="122" ry="12" fill="rgba(0,0,0,.18)" /><g className="scene-mascot"><path d="M45 143V86c0-42 26-66 59-66s59 24 59 66v57c-20 15-96 15-118 0Z" fill="#39334d" /><path d="M62 87c0-30 17-49 42-49s42 19 42 49v45c-11 11-31 16-42 16s-31-5-42-16V87Z" fill="#181822" /><path d="M70 75c12-25 51-33 69 1" fill="none" stroke="#655777" strokeLinecap="round" strokeWidth="12" /><circle cx="88" cy="96" r="6" fill="#ffcc63" /><circle cx="121" cy="96" r="6" fill="#ffcc63" /><path d={sad ? 'M96 120 Q104 112 112 120' : 'M96 114 Q104 122 112 114'} fill="none" stroke="#ffcc63" strokeLinecap="round" strokeWidth="3" /><path d="M68 137c-13 3-20 13-22 24" fill="none" stroke="#51486b" strokeLinecap="round" strokeWidth="13" /><path d="M140 137c13 3 20 13 22 24" fill="none" stroke="#51486b" strokeLinecap="round" strokeWidth="13" /></g><g className="scene-logs"><rect x="170" y="142" width="82" height="12" rx="6" fill="#70452f" transform="rotate(10 170 142)" /><rect x="171" y="142" width="82" height="12" rx="6" fill="#8f5a36" transform="rotate(-10 171 142)" /></g>{level > 0 && <g className="scene-fire" transform={`translate(203 141) scale(${fireScale})`}><path d="M0 0C-24-26 2-55 7-77c23 22 39 39 22 77Z" fill="#f4792d" /><path d="M1-3C-7-26 8-42 11-54c12 15 19 29 10 51Z" fill="#ffd45b" /></g>}</svg>
}

function MonthlyComparison({ metrics }: { metrics: { label: string; current: number; previous: number }[] }) { const max = Math.max(1, ...metrics.flatMap(item => [item.current, item.previous])); return <section className="monthly-progress"><div className="chart-title"><div><p className="eyebrow">COMPARAÇÃO</p><h2>Este mês x mês anterior</h2></div><span>evolução mensal</span></div><div className="monthly-bars">{metrics.map(item => <div className="monthly-metric" key={item.label}><div className="monthly-values"><strong>{item.current}</strong><span>vs {item.previous}</span></div><div className="bar-pair" title={`${item.label}: ${item.current} este mês, ${item.previous} mês anterior`}><i style={{ height: `${Math.max(5, item.current / max * 100)}%` }} /><b style={{ height: `${Math.max(5, item.previous / max * 100)}%` }} /></div><small>{item.label}</small></div>)}</div><div className="chart-legend"><span><i className="legend-current" /> Este mês</span><span><i className="legend-previous" /> Mês anterior</span></div></section> }
function ActivityChart({ values }: { values: { date: string; amount: number }[] }) { const max = Math.max(1, ...values.map(item => item.amount)); const width = 620; const gap = 10; const barWidth = (width - gap * (values.length + 1)) / values.length; return <article className="activity-chart"><div className="chart-title"><div><p className="eyebrow">ATIVIDADE</p><h2>Últimos 14 dias</h2></div><span>hábitos concluídos</span></div><svg role="img" aria-label="Gráfico de hábitos concluídos nos últimos catorze dias" viewBox={`0 0 ${width} 210`}><line x1="0" x2={width} y1="170" y2="170" className="chart-axis" />{values.map((item, index) => { const h = item.amount / max * 132; const x = gap + index * (barWidth + gap); return <g key={item.date}><rect className="chart-bar" x={x} y={170 - h} width={barWidth} height={h} rx="4" /><text x={x + barWidth / 2} y="194" textAnchor="middle">{shortDay(item.date)}</text></g> })}</svg></article> }
function Calendar({ activeDates }: { activeDates: Set<string> }) { const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: offset + days }, (_, i) => i < offset ? null : i - offset + 1); return <article className="calendar"><div className="calendar-weekdays">{weekdays.map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map((day, i) => { if (!day) return <i key={`empty-${i}`} />; const key = localDate(now.getFullYear(), now.getMonth(), day); const done = activeDates.has(key); return <div className={`calendar-day ${done ? 'done' : ''} ${key === today() ? 'today' : ''}`} key={key}><span>{day}</span>{done && <b>•</b>}</div> })}</div><div className="calendar-legend"><span><i className="legend-active" /> Atividade concluída</span><span><i className="legend-today" /> Hoje</span></div></article> }
function monthRange(year: number, month: number) { const start = new Date(year, month, 1, 12); const end = new Date(year, month + 1, 0, 12); return { start: localDate(start.getFullYear(), start.getMonth(), 1), end: localDate(end.getFullYear(), end.getMonth(), end.getDate()) } }
function uniqueCompleted(logs: ReturnType<typeof getLocalHabitLogs>, range: { start: string; end: string }) { return new Set(logs.filter(log => log.status === 'completed' && log.date >= range.start && log.date <= range.end).map(log => log.date)).size }
function pagesIn(sessions: ReturnType<typeof getLocalReadingSessions>, range: { start: string; end: string }) { return sessions.filter(item => item.started_at.slice(0, 10) >= range.start && item.started_at.slice(0, 10) <= range.end).reduce((sum, item) => sum + item.pages_read, 0) }
function countIn(items: ReturnType<typeof getLocalCheckIns>, range: { start: string; end: string }) { return items.filter(item => item.date >= range.start && item.date <= range.end).length }
function recentDays(count: number) { const result: string[] = []; const now = new Date(); for (let i = count - 1; i >= 0; i--) { const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i); result.push(localDate(d.getFullYear(), d.getMonth(), d.getDate())) } return result }
function localDate(year: number, month: number, day: number) { return new Date(year, month, day, 12).toLocaleDateString('en-CA') }
function shortDay(date: string) { return new Intl.DateTimeFormat('pt-BR', { weekday: 'narrow' }).format(new Date(`${date}T12:00:00`)) }
function monthLabel() { return new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date()) }
