import { getLocalCheckIns, getLocalHabitLogs, getLocalReadingSessions, overallStreak, today } from '../lib/local-store'
import { useLocalRevision } from '../lib/use-local-revision'

const weekdays = ['Seg', 'Ter', 'Qua', 'Qui', 'Sex', 'Sáb', 'Dom']

export function Progress() {
  useLocalRevision()
  const logs = getLocalHabitLogs(); const sessions = getLocalReadingSessions(); const checkins = getLocalCheckIns()
  const now = new Date(); const current = monthRange(now.getFullYear(), now.getMonth()); const previous = monthRange(now.getFullYear(), now.getMonth() - 1)
  const streak = overallStreak(logs); const days = recentDays(14); const active = new Set(logs.filter(log => log.status === 'completed').map(log => log.date))
  const chart = days.map(date => ({ date, amount: logs.filter(log => log.date === date && log.status === 'completed').length }))
  const metrics = [{ label: 'Dias ativos', current: uniqueCompleted(logs, current), previous: uniqueCompleted(logs, previous) }, { label: 'Páginas lidas', current: pagesIn(sessions, current), previous: pagesIn(sessions, previous) }, { label: 'Check-ins', current: countIn(checkins, current), previous: countIn(checkins, previous) }]
  return <><header><p className="eyebrow">VISÃO GERAL</p><h1>Seu progresso</h1><p>Consistência se constrói dia após dia.</p></header><section className="visual-summary"><article className="streak-hero"><span>Sequência atual</span><strong>{streak}</strong><small>dias consecutivos</small></article><ActivityChart values={chart} /></section><MonthlyComparison metrics={metrics} /><section className="calendar-section"><div><p className="eyebrow">CALENDÁRIO</p><h2>{monthLabel()}</h2></div><Calendar activeDates={active} /></section></>
}

function MonthlyComparison({ metrics }: { metrics: { label: string; current: number; previous: number }[] }) { const max = Math.max(1, ...metrics.flatMap(item => [item.current, item.previous])); return <section className="monthly-progress"><div className="chart-title"><div><p className="eyebrow">COMPARAÇÃO</p><h2>Este mês x mês anterior</h2></div><span>evolução mensal</span></div><div className="monthly-bars">{metrics.map(item => <div className="monthly-metric" key={item.label}><div className="monthly-values"><strong>{item.current}</strong><span>vs {item.previous}</span></div><div className="bar-pair" title={`${item.label}: ${item.current} este mês, ${item.previous} mês anterior`}><i style={{ height: `${Math.max(5, item.current / max * 100)}%` }} /><b style={{ height: `${Math.max(5, item.previous / max * 100)}%` }} /></div><small>{item.label}</small></div>)}</div><div className="chart-legend"><span><i className="legend-current" /> Este mês</span><span><i className="legend-previous" /> Mês anterior</span></div></section> }
function ActivityChart({ values }: { values: { date: string; amount: number }[] }) { const max = Math.max(1, ...values.map(item => item.amount)); const width = 620; const gap = 10; const barWidth = (width - gap * (values.length + 1)) / values.length; return <article className="activity-chart"><div className="chart-title"><div><p className="eyebrow">ATIVIDADE</p><h2>Últimos 14 dias</h2></div><span>hábitos concluídos</span></div><svg role="img" aria-label="Gráfico de hábitos concluídos nos últimos catorze dias" viewBox={`0 0 ${width} 210`}><line x1="0" x2={width} y1="170" y2="170" className="chart-axis" />{values.map((item, index) => { const h = item.amount / max * 132; const x = gap + index * (barWidth + gap); return <g key={item.date}><rect className="chart-bar" x={x} y={170 - h} width={barWidth} height={h} rx="4" /><text x={x + barWidth / 2} y="194" textAnchor="middle">{shortDay(item.date)}</text></g> })}</svg></article> }
function Calendar({ activeDates }: { activeDates: Set<string> }) { const now = new Date(); const first = new Date(now.getFullYear(), now.getMonth(), 1); const offset = (first.getDay() + 6) % 7; const days = new Date(now.getFullYear(), now.getMonth() + 1, 0).getDate(); const cells = Array.from({ length: offset + days }, (_, i) => i < offset ? null : i - offset + 1); return <article className="calendar"><div className="calendar-weekdays">{weekdays.map(day => <span key={day}>{day}</span>)}</div><div className="calendar-grid">{cells.map((day, i) => { if (!day) return <i key={`empty-${i}`} />; const key = localDate(now.getFullYear(), now.getMonth(), day); const done = activeDates.has(key); return <div className={`calendar-day ${done ? 'done' : ''} ${key === today() ? 'today' : ''}`} key={key}><span>{day}</span>{done && <b>•</b>}</div> })}</div><div className="calendar-legend"><span><i className="legend-active" /> Atividade concluída</span><span><i className="legend-today" /> Hoje</span></div></article> }
function monthRange(year: number, month: number) { const start = new Date(year, month, 1, 12); const end = new Date(year, month + 1, 0, 12); return { start: localDate(start.getFullYear(), start.getMonth(), 1), end: localDate(end.getFullYear(), end.getMonth(), end.getDate()) } }
function uniqueCompleted(logs: ReturnType<typeof getLocalHabitLogs>, range: { start: string; end: string }) { return new Set(logs.filter(log => log.status === 'completed' && log.date >= range.start && log.date <= range.end).map(log => log.date)).size }
function pagesIn(sessions: ReturnType<typeof getLocalReadingSessions>, range: { start: string; end: string }) { return sessions.filter(item => item.started_at.slice(0, 10) >= range.start && item.started_at.slice(0, 10) <= range.end).reduce((sum, item) => sum + item.pages_read, 0) }
function countIn(items: ReturnType<typeof getLocalCheckIns>, range: { start: string; end: string }) { return items.filter(item => item.date >= range.start && item.date <= range.end).length }
function recentDays(count: number) { const result: string[] = []; const now = new Date(); for (let i = count - 1; i >= 0; i--) { const d = new Date(now.getFullYear(), now.getMonth(), now.getDate() - i); result.push(localDate(d.getFullYear(), d.getMonth(), d.getDate())) } return result }
function localDate(year: number, month: number, day: number) { return new Date(year, month, day, 12).toLocaleDateString('en-CA') }
function shortDay(date: string) { return new Intl.DateTimeFormat('pt-BR', { weekday: 'narrow' }).format(new Date(`${date}T12:00:00`)) }
function monthLabel() { return new Intl.DateTimeFormat('pt-BR', { month: 'long', year: 'numeric' }).format(new Date()) }
