import type { Challenge, ChallengeRule, ChallengeType } from '../domain/challenge'

type Template = { id: string; name: string; description: string; type: ChallengeType; durationDays: number; rules: Omit<ChallengeRule, 'id'>[] }
export const challengeTemplates: Template[] = [
  { id: 'beginner', name: 'Caverna Iniciante', description: 'Sete dias para acender a primeira chama.', type: 'HABITS', durationDays: 7, rules: [{ type: 'HABIT', title: 'Completar hábitos', target: 3, unit: 'hábitos', frequency: 'DAILY' }, { type: 'READING_PAGES', title: 'Ler', target: 5, unit: 'páginas', frequency: 'DAILY' }, { type: 'CHECK_IN', title: 'Check-in', target: 1, unit: 'check-in', frequency: 'DAILY' }] },
  { id: 'focus', name: 'Caverna de Foco', description: 'Duas semanas para proteger sua atenção.', type: 'FOCUS', durationDays: 14, rules: [{ type: 'FOCUS_MINUTES', title: 'Foco profundo', target: 60, unit: 'min', frequency: 'DAILY' }, { type: 'CHECK_IN', title: 'Check-in', target: 1, unit: 'check-in', frequency: 'DAILY' }] },
  { id: 'fitness', name: 'Caverna Fitness', description: 'Trinta dias de corpo em movimento.', type: 'FITNESS', durationDays: 30, rules: [{ type: 'WORKOUT', title: 'Academia', target: 4, unit: 'treinos', frequency: 'WEEKLY' }, { type: 'HABIT', title: 'Hábito de saúde', target: 1, unit: 'hábito', frequency: 'DAILY' }] },
  { id: 'reading', name: 'Caverna de Leitura', description: 'Trinta dias para avançar sua biblioteca.', type: 'READING', durationDays: 30, rules: [{ type: 'READING_PAGES', title: 'Ler', target: 10, unit: 'páginas', frequency: 'DAILY' }, { type: 'READING_PAGES', title: 'Páginas no ciclo', target: 300, unit: 'páginas', frequency: 'TOTAL' }] },
  { id: 'complete', name: 'Caverna Completa', description: 'Um ciclo equilibrado para disciplina integral.', type: 'FULL_CAVERN', durationDays: 30, rules: [{ type: 'WORKOUT', title: 'Academia', target: 4, unit: 'treinos', frequency: 'WEEKLY' }, { type: 'FOCUS_MINUTES', title: 'Estudo profundo', target: 60, unit: 'min', frequency: 'DAILY' }, { type: 'READING_PAGES', title: 'Leitura', target: 10, unit: 'páginas', frequency: 'DAILY' }, { type: 'CHECK_IN', title: 'Check-in', target: 1, unit: 'check-in', frequency: 'DAILY' }] },
]

export function challengeFromTemplate(template: Template, startDate: string): Challenge { const endDate = shift(startDate, template.durationDays - 1); return { id: crypto.randomUUID(), name: template.name, description: template.description, type: template.type, difficulty: 'NORMAL', status: 'DRAFT', startDate, endDate, durationDays: template.durationDays, rules: template.rules.map(rule => ({ ...rule, id: crypto.randomUUID() })), checkpoints: checkpoints(template.durationDays), rewards: [{ title: 'Ciclo concluído', xp: 500 }], createdAt: new Date().toISOString() } }
export function checkpoints(days: number) { return [...new Set([Math.ceil(days / 4), Math.ceil(days / 2), Math.ceil(days * .75), days])].map((day, index) => ({ day, title: ['Primeira chama', 'Consistência', 'Disciplina', 'Habitante da Caverna'][index] ?? 'Marco' })) }
function shift(date: string, amount: number) { const value = new Date(`${date}T12:00:00`); value.setDate(value.getDate() + amount); return value.toLocaleDateString('en-CA') }
