import { useRef, useState } from 'react'
import { readDatabaseValue, setDatabaseValue } from '../lib/app-db'
import { localDataKeys } from '../lib/local-store'

const backupVersion = 1
export function BackupSettings() {
  const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState('')
  async function download() { const records = await Promise.all(Object.values(localDataKeys).map(async key => [key, await readDatabaseValue(key)])); const avatar = await readDatabaseValue('cavern.profile.avatar.v1'); const blob = new Blob([JSON.stringify({ version: backupVersion, createdAt: new Date().toISOString(), records: Object.fromEntries(records), avatar }, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `cavern-backup-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(url); setMessage('Backup exportado.') }
  async function restore(file?: File) { if (!file) return; try { const data = JSON.parse(await file.text()); if (data.version !== backupVersion || !data.records || typeof data.records !== 'object') throw new Error(); if (!window.confirm('Restaurar este backup substituirá os dados locais atuais. Continuar?')) return; await Promise.all(Object.values(localDataKeys).map(key => { if (data.records[key] === undefined) return Promise.resolve(); localStorage.setItem(key, JSON.stringify(data.records[key])); return setDatabaseValue(key, data.records[key]) })); if (typeof data.avatar === 'string') await setDatabaseValue('cavern.profile.avatar.v1', data.avatar); setMessage('Backup restaurado. Recarregue o aplicativo para ver todos os dados.'); } catch { setMessage('Arquivo de backup inválido.') } }
  return <section className="panel profile-section"><h2>Backup local</h2><p className="profile-note">Exporte seus dados para trocar de navegador ou manter uma cópia segura.</p><div className="button-row"><button type="button" className="subtle" onClick={() => void download()}>Exportar backup</button><button type="button" className="subtle" onClick={() => input.current?.click()}>Importar backup</button></div><input ref={input} className="sr-only" aria-label="Importar arquivo de backup" type="file" accept="application/json" onChange={event => void restore(event.target.files?.[0])}/>{message && <p className="saved-message" role="status">{message}</p>}</section>
}
